// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sum_vec_1
NumericVector sum_vec_1(NumericVector x, NumericVector y);
RcppExport SEXP anRpackage_sum_vec_1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sum_vec_1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// sum_vec_3
NumericVector sum_vec_3(NumericVector x, NumericVector y);
RcppExport SEXP anRpackage_sum_vec_3(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sum_vec_3(x, y));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP pcaMatrix__center_scale(SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__crossprodvect(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__extract_matrix(SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__extract_vector(SEXP, SEXP);
RcppExport SEXP pcaMatrix__new(SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__prodvect(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"anRpackage_sum_vec_1", (DL_FUNC) &anRpackage_sum_vec_1, 2},
    {"anRpackage_sum_vec_3", (DL_FUNC) &anRpackage_sum_vec_3, 2},
    {"pcaMatrix__center_scale",   (DL_FUNC) &pcaMatrix__center_scale,   3},
    {"pcaMatrix__crossprodvect",  (DL_FUNC) &pcaMatrix__crossprodvect,  4},
    {"pcaMatrix__extract_matrix", (DL_FUNC) &pcaMatrix__extract_matrix, 3},
    {"pcaMatrix__extract_vector", (DL_FUNC) &pcaMatrix__extract_vector, 2},
    {"pcaMatrix__new",            (DL_FUNC) &pcaMatrix__new,            3},
    {"pcaMatrix__prodvect",       (DL_FUNC) &pcaMatrix__prodvect,       4},
    {NULL, NULL, 0}
};

RcppExport void R_init_anRpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
