// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP anRpackage_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP pcaMatrix__crossprodvect(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__extract_matrix(SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__extract_vector(SEXP, SEXP);
RcppExport SEXP pcaMatrix__new(SEXP, SEXP, SEXP);
RcppExport SEXP pcaMatrix__prodvect(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"anRpackage_rcpp_hello_world", (DL_FUNC) &anRpackage_rcpp_hello_world, 0},
    {"pcaMatrix__crossprodvect",    (DL_FUNC) &pcaMatrix__crossprodvect,    4},
    {"pcaMatrix__extract_matrix",   (DL_FUNC) &pcaMatrix__extract_matrix,   3},
    {"pcaMatrix__extract_vector",   (DL_FUNC) &pcaMatrix__extract_vector,   2},
    {"pcaMatrix__new",              (DL_FUNC) &pcaMatrix__new,              3},
    {"pcaMatrix__prodvect",         (DL_FUNC) &pcaMatrix__prodvect,         4},
    {NULL, NULL, 0}
};

RcppExport void R_init_anRpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
