# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_vec_1 <- function(x, y) {
    .Call(anRpackage_sum_vec_1, x, y)
}

sum_vec_3 <- function(x, y) {
    .Call(anRpackage_sum_vec_3, x, y)
}

